name: SkunkPlatform CLI Builder

on: [push]

jobs:
  build:
    name: Build (${{ matrix.platform }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: win64
            os: windows-latest
            exec_path: build/examplecli.exe
            artifact_name: examplecli-win64.exe
          - platform: linux64
            os: ubuntu-latest
            exec_path: build/examplecli
            artifact_name: examplecli-linux64
          - platform: macos64
            os: macos-latest
            exec_path: build/examplecli
            artifact_name: examplecli-macos64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js v24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install postject

      - name: Build Executable
        run: node skunkbuilder/building.js

      - name: Upload Build Artifact
        if: hashFiles(matrix.exec_path) != ''
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.exec_path }}
          retention-days: 1
